# Amazon Personalize ハンズオン
* 本ハンズオンは Personalize で レコメンデーションするために必要な工程を一通り体験するハンズオンです
* 実行環境の前提として SageMaker Notebook Instance で Jupyter Notebook を使用します
* 構成は下記の通り

## 手順概要

0. SageMaker Notebook Instance を立ち上げ、Jupyter Notebook を開いてこのノートブックを開く
1. Personalize にデータを取り込むための S3 バケットを作成する
2. S3 のバケットポリシーを設定し、 Amazon Personalize のサービスが アップロードしたデータにアクセスできるようにする
3. Amazon Personalize の実行ロールを作成し、Amazon Personalize のサービスが使えるようにする
4. S3 にデータをアップロードする
5. S3 から Personalize へデータをインポートするためにスキーマ定義を行い、インポートする
6. ソリューションとバージョンを作成する(学習)
7. 作成したソリューションバージョンからキャンペーンを作成する（ホスティング）
8. 作成したキャンペーンでレコメンデーション機能を試す

<img src="./media/diagram.png">

## 環境準備

### 本ハンズオンで利用するライブラリの読み込み

In [1]:
from IPython.core.display import display, HTML 
display(HTML("<style>.container { width:97% !important; }</style>")) 
import boto3,json,time
from datetime import date,datetime
import pandas as pd
import numpy as np

### 学習データ保存用S3バケットの作成
#### 概要
* Personalizeがデータインポート時、推論結果出力時に利用するS3バケットの作成と設定を行う
* 作成したバケットに対して、Amazon Personlize のサービスがアクセスできるようバケットポリシーを設定する

* 本ハンズオンでは personlize-handson-${yourname}-YYYY-MM-DD-hh-mm-ss というバケット名を作成して、利用する
* 下記セルの yourname 変数に任意の名前を入力する

#### 設定値を変数に格納する

In [2]:
# 各設定値を変数に格納する

#------下記変数をご自身の名前で必ず設定ください------#
#----------------------------------------------------#
yourname = 'gokazu' #   <- ここに記入をお願いします
#----------------------------------------------------#
#----------------------------------------------------#

# region は 東京リージョンを利用します
region = 'ap-northeast-1'
# 説明分の通りのバケット名を bucket_name 変数に格納します
timestamp = datetime.now().strftime('-%Y-%m-%d-%H-%M-%S')
bucket_name = 'personalize-handson-' + yourname + timestamp
print(f'本ハンズオンで利用する\nバケットは "{bucket_name}"')
print(f'リージョンは "{region}"\nです')

本ハンズオンで利用する
バケットは "personalize-handson-gokazu-2020-11-12-11-51-18"
リージョンは "ap-northeast-1"
です

#### bucket 作成
boto3 の s3 [client](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.BucketPolicy.put) の [create_bucket](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.create_bucket) メソッド を利用して作成する

In [3]:
s3_client = boto3.client('s3')
location = {'LocationConstraint': region}
response = s3_client.create_bucket(
    Bucket = bucket_name,
    CreateBucketConfiguration = location
)
print(json.dumps(response, indent=2))

{
  "ResponseMetadata": {
    "RequestId": "1C51F1295C0094CD",
    "HostId": "uqMmokrLpRuTFM/3ZPLxfFzzSqgb78DSxuR2iAlc74E+OlrL9F3gg/Ihqum2hl8WCWk1mMTdDi8=",
    "HTTPStatusCode": 200,
    "HTTPHeaders": {
      "x-amz-id-2": "uqMmokrLpRuTFM/3ZPLxfFzzSqgb78DSxuR2iAlc74E+OlrL9F3gg/Ihqum2hl8WCWk1mMTdDi8=",
      "x-amz-request-id": "1C51F1295C0094CD",
      "date": "Thu, 12 Nov 2020 11:51:21 GMT",
      "location": "http://personalize-handson-gokazu-2020-11-12-11-51-18.s3.amazonaws.com/",
      "content-length": "0",
      "server": "AmazonS3"
    },
    "RetryAttempts": 0
  },
  "Location": "http://personalize-handson-gokazu-2020-11-12-11-51-18.s3.amazonaws.com/"
}

#### バケットポリシーの設定
* Amazon Personalize のサービスが作成した S3 バケットにアクセスできるようバケットポリシーを設定する
* バケットポリシー は [BucketPolicy](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.ServiceResource.BucketPolicy) の [put](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.BucketPolicy.put) メソッドで json 形式で設定する

In [4]:
# bucket policy 設定
bucket_policy = boto3.resource('s3').BucketPolicy(bucket_name)

policy = {
    "Version": "2012-10-17",
    "Id": "PersonalizeS3Bucket AccessPolicy",
    "Statement": [
        {
            "Sid": "PersonalizeS3BucketAccessPolicy",
            "Effect": "Allow",
            "Principal": {
                "Service": "personalize.amazonaws.com"
            },
            "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::" + bucket_name,
                "arn:aws:s3:::" + bucket_name +"/*"
            ]
        }
    ]
}

policy = json.dumps(policy)

response = bucket_policy.put(
    Policy=policy
)
print(json.dumps(response, indent=2))

{
  "ResponseMetadata": {
    "RequestId": "24495D2C99448310",
    "HostId": "TDrpRyelHJhVTg3gXZhqG1i8pxWcz+XNJAvhqYD0yIlF63vls6N04au8nLQ1mZ6R/HybadfZgvA=",
    "HTTPStatusCode": 204,
    "HTTPHeaders": {
      "x-amz-id-2": "TDrpRyelHJhVTg3gXZhqG1i8pxWcz+XNJAvhqYD0yIlF63vls6N04au8nLQ1mZ6R/HybadfZgvA=",
      "x-amz-request-id": "24495D2C99448310",
      "date": "Thu, 12 Nov 2020 11:51:22 GMT",
      "server": "AmazonS3"
    },
    "RetryAttempts": 0
  }
}

#### key_prefix の設定
本ハンズオンで利用する bucket の key_prefix を設定する

In [5]:
# 後続処理で利用するS3のprefixを指定
s3_key_prefix = 'personalize-demo' + timestamp + '/'
print(f'今日のハンズオンで利用する key prefix は "{s3_key_prefix}" です')

今日のハンズオンで利用する key prefix は "personalize-demo-2020-11-12-11-51-18/" です

### Personalize実行ロールの作成
* [Amazon Personalize 用の IAM ロールの作成](https://docs.aws.amazon.com/ja_jp/personalize/latest/dg/aws-personalize-set-up-permissions.html#set-up-required-permissions)パートの手順に従ってPersonalizeの実行ロールを作成する
* IAM ロールの作成は、 boto3 の [create_role](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/iam.html#IAM.Client.create_role) メソッドを利用して作成する
* 作成した IAM ロールに AmazonPersonalizeFullAccess ポリシーを [attach_role_policy](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/iam.html#IAM.Client.attach_role_policy) でアタッチする
* 作成した Personalize ロールの ARN を変数に格納する

In [6]:
# ロール作成
iam = boto3.client('iam')

assume_role_policy_document = {
    'Version': '2012-10-17',
    'Statement': [{'Sid': '','Effect': 'Allow','Principal': {'Service': 'personalize.amazonaws.com'},'Action': 'sts:AssumeRole'}]
}

response = iam.create_role(
    RoleName = 'personalizeRole' + timestamp,
    AssumeRolePolicyDocument = json.dumps(assume_role_policy_document),
    Description='using Amazon Personalize handson '+ timestamp.replace('-',''),
    MaxSessionDuration=3600*12 # 12時間
)
role_arn = response['Role']['Arn']
role_name = response['Role']['RoleName']

print(f'作成した role の\narn は "{role_arn}"')
print(f'名前は "{role_name}"\nです')

作成した role の
arn は "arn:aws:iam::155580384669:role/personalizeRole-2020-11-12-11-51-18"
名前は "personalizeRole-2020-11-12-11-51-18"
です

In [7]:
# Policy attach
response = iam.attach_role_policy(
    RoleName=role_name,
    PolicyArn='arn:aws:iam::aws:policy/service-role/AmazonPersonalizeFullAccess'
)
print(json.dumps(response, indent=2))

{
  "ResponseMetadata": {
    "RequestId": "da05f86d-364f-4c1c-8d59-3a0d936c0755",
    "HTTPStatusCode": 200,
    "HTTPHeaders": {
      "x-amzn-requestid": "da05f86d-364f-4c1c-8d59-3a0d936c0755",
      "content-type": "text/xml",
      "content-length": "212",
      "date": "Thu, 12 Nov 2020 11:51:22 GMT"
    },
    "RetryAttempts": 0
  }
}

### Personalize boto3 Clientの設定

In [8]:
# Personalize を操作するための client を生成
personalize = boto3.client(service_name='personalize')
personalize_runtime = boto3.client(service_name='personalize-runtime')
personalize_events = boto3.client(service_name='personalize-events')

## データの確認

#### サンプルデータ
* Movielensの10万件の評価データを Personalize で利用できるように事前にデータを加工済
* どのようなデータ形式になっているかを確認する
* 処理内容については本ハンズオンでは扱わないが、[こちら](./data_preparation.ipynb)のノートブックに記載

##### Interaction Data
* ユーザがいつどの映画を見たのかを示すデータ
* レコメンドに評価の低かった映画は出したくないので、レートが4以上のものにフィルタしている
* 必須項目は USER_ID,ITEM_ID,TIMESTAMP

In [9]:
pd.read_csv('./data/interaction.csv').sort_values(['USER_ID','TIMESTAMP']).reset_index().drop(columns='index').head(50)

    USER_ID  ITEM_ID EVENT_TYPE  EVENT_VALUE  TIMESTAMP
0         1      250     RATING            4  874965706
1         1      253     RATING            5  874965970
2         1      224     RATING            5  875071484
3         1      124     RATING            5  875071484
4         1      123     RATING            4  875071541
5         1      236     RATING            4  875071898
6         1      183     RATING            5  875072262
7         1       64     RATING            5  875072404
8         1      151     RATING            4  875072865
9         1      197     RATING            5  875072956
10        1      186     RATING            4  875073128
11        1      174     RATING            5  875073198
12        1       42     RATING            5  876892425
13        1      177     RATING            5  876892701
14        1      157     RATING            4  876892918
15        1      173     RATING            5  878541803
16        1       90     RATING            4  878542300
17        1      152     RATING            5  878542589
18        1      208     RATING            5  878542960
19        1       66     RATING            4  878543030
20        1      241     RATING            4  878543133
21        1       75     RATING            4  878543238
22        1      228     RATING            5  878543541
23        1       16     RATING            5  878543541
24        1      222     RATING            4  878873388
25        1       32     RATING            5  888732909
26        2      269     RATING            4  888550774
27        2      303     RATING            4  888550774
28        2      275     RATING            5  888550939
29        2      293     RATING            4  888550939
30        2      257     RATING            4  888551062
31        2      295     RATING            4  888551164
32        2      277     RATING            4  888551174
33        2       25     RATING            4  888551648
34        2      313     RATING            5  888552084
35        3      344     RATING            4  889236939
36        3      329     RATING            4  889237455
37        3      340     RATING            5  889237455
38        3      347     RATING            5  889237455
39        3      181     RATING            4  889237482
40        4      288     RATING            4  892001445
41        4       50     RATING            5  892003526
42        5      267     RATING            4  875635064
43        5       42     RATING            5  875636360
44        5      422     RATING            4  875636767
45        5      436     RATING            5  875720717
46        5      443     RATING            4  875720744
47        5       95     RATING            4  875721168
48        5      408     RATING            5  878844495
49        5       24     RATING            4  879198229

##### Item Data
* アイテムの属性を表すデータ
* 複数の属性を含む場合は一つの列に|(パイプ)で区切って格納する
* 必須項目は ITEM_ID と、1 つ以上の属性情報(今回は GENRE )

In [10]:
pd.read_csv('./data/item.csv').head(50)

    ITEM_ID                                     GENRE
0         1               Animation|Children's|Comedy
1         2                 Action|Adventure|Thriller
2         3                                  Thriller
3         4                       Action|Comedy|Drama
4         5                      Crime|Drama|Thriller
5         6                                     Drama
6         7                              Drama|Sci-Fi
7         8                   Children's|Comedy|Drama
8         9                                     Drama
9        10                                 Drama|War
10       11                            Crime|Thriller
11       12                            Crime|Thriller
12       13                                    Comedy
13       14                             Drama|Romance
14       15                                     Drama
15       16                            Comedy|Romance
16       17       Action|Comedy|Crime|Horror|Thriller
17       18                                     Drama
18       19                                     Drama
19       20                             Drama|Romance
20       21  Action|Adventure|Comedy|Musical|Thriller
21       22                          Action|Drama|War
22       23                            Drama|Thriller
23       24                    Action|Adventure|Crime
24       25                                    Comedy
25       26                                    Comedy
26       27                                    Action
27       28                     Action|Drama|Thriller
28       29             Action|Adventure|Comedy|Crime
29       30                                     Drama
30       31                        Drama|Thriller|War
31       32                               Documentary
32       33                   Action|Romance|Thriller
33       34                              Comedy|Drama
34       35                Adventure|Children's|Drama
35       36                             Drama|Romance
36       37                                     Drama
37       38                           Sci-Fi|Thriller
38       39                       Action|Crime|Sci-Fi
39       40                                    Comedy
40       41                                    Comedy
41       42                                    Comedy
42       43                            Drama|Thriller
43       44                            Drama|Thriller
44       45                              Comedy|Drama
45       46                                     Drama
46       47                              Comedy|Drama
47       48                               Documentary
48       49                            Comedy|Romance
49       50       Action|Adventure|Romance|Sci-Fi|War

##### User Data
* ユーザの属性を表すデータ
* 必須項目は USER_ID と、1 つ以上の属性情報
* このデータでは年齢、性別、職業、郵便番号を含む

In [11]:
pd.read_csv('./data/user.csv').head(50)

    USER_ID  AGE GENDER            JOB    ZIP
0         1   24      M     technician  85711
1         2   53      F          other  94043
2         3   23      M         writer  32067
3         4   24      M     technician  43537
4         5   33      F          other  15213
5         6   42      M      executive  98101
6         7   57      M  administrator  91344
7         8   36      M  administrator  05201
8         9   29      M        student  01002
9        10   53      M         lawyer  90703
10       11   39      F          other  30329
11       12   28      F          other  06405
12       13   47      M       educator  29206
13       14   45      M      scientist  55106
14       15   49      F       educator  97301
15       16   21      M  entertainment  10309
16       17   30      M     programmer  06355
17       18   35      F          other  37212
18       19   40      M      librarian  02138
19       20   42      F      homemaker  95660
20       21   26      M         writer  30068
21       22   25      M         writer  40206
22       23   30      F         artist  48197
23       24   21      F         artist  94533
24       25   39      M       engineer  55107
25       26   49      M       engineer  21044
26       27   40      F      librarian  30030
27       28   32      M         writer  55369
28       29   41      M     programmer  94043
29       30    7      M        student  55436
30       31   24      M         artist  10003
31       32   28      F        student  78741
32       33   23      M        student  27510
33       34   38      F  administrator  42141
34       35   20      F      homemaker  42459
35       36   19      F        student  93117
36       37   23      M        student  55105
37       38   28      F          other  54467
38       39   41      M  entertainment  01040
39       40   38      M      scientist  27514
40       41   33      M       engineer  80525
41       42   30      M  administrator  17870
42       43   29      F      librarian  20854
43       44   26      M     technician  46260
44       45   29      M     programmer  50233
45       46   27      F      marketing  46538
46       47   53      M      marketing  07102
47       48   45      M  administrator  12550
48       49   23      F        student  76111
49       50   21      M         writer  52245

##### Interaction Data, Item Data, User Data の 3 つを S3 にアップロードする
* 確認した 3 ファイルを事前に設定したバケット、key_prefix にアップロードする
* アップロードには [upload_file](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Object.upload_file) を用いる(アップロードするためのメソッドは多種あるがアップロードされればどれでもよい）

In [12]:
boto3.Session().resource('s3').Bucket(bucket_name).Object(s3_key_prefix + 'interaction.csv').upload_file('./data/interaction.csv')
boto3.Session().resource('s3').Bucket(bucket_name).Object(s3_key_prefix + 'item.csv').upload_file('./data/item.csv')
boto3.Session().resource('s3').Bucket(bucket_name).Object(s3_key_prefix + 'user.csv').upload_file('./data/user.csv')

### Personalize 環境の準備

まずはデータをインポートするためにデータのスキーマ定義とデータセットグループの作成を行う

#### インタラクションスキーマの定義
* インタラクションデータの csv に沿ったデータスキーマを設定
* 必須項目はアップロードした csv 同様、USER_ID, ITEM_ID, TIME_STAMP の 3 種

インタラクションスキーマの[参考情報](https://docs.aws.amazon.com/personalize/latest/dg/schema-examples-interactions.html)

In [13]:
now = datetime.now()
time_str = now.strftime("-%Y-%m-%d-%H-%M-%S")

interaction_schema = {
    "type": "record",
    "name": "Interactions",
    "namespace": "com.amazonaws.personalize.schema",
    "fields": [
        {
            "name": "USER_ID",
            "type": "string"
        },
        {
            "name": "ITEM_ID",
            "type": "string"
        },
        {
            "name": "EVENT_TYPE",
            "type": "string"
        },
        {
            "name": "EVENT_VALUE",
            "type": [
             "float",
             "null"
          ]
        },
        {
            "name": "TIMESTAMP",
            "type": "long"
        }
    ],
    "version": "1.0"
}

create_interaction_schema_response = personalize.create_schema(
    name = "DEMO-movielens-interaction-schema" + time_str,
    schema = json.dumps(interaction_schema)
)

interaction_schema_arn = create_interaction_schema_response['schemaArn']
print(json.dumps(create_interaction_schema_response, indent=2))

{
  "schemaArn": "arn:aws:personalize:ap-northeast-1:155580384669:schema/DEMO-movielens-interaction-schema-2020-11-12-11-51-27",
  "ResponseMetadata": {
    "RequestId": "197f1587-eefc-4b94-8358-824158c0d7dc",
    "HTTPStatusCode": 200,
    "HTTPHeaders": {
      "content-type": "application/x-amz-json-1.1",
      "date": "Thu, 12 Nov 2020 11:51:27 GMT",
      "x-amzn-requestid": "197f1587-eefc-4b94-8358-824158c0d7dc",
      "content-length": "124",
      "connection": "keep-alive"
    },
    "RetryAttempts": 0
  }
}

#### アイテムスキーマの定義

* アイテムデータの csv に沿ったデータスキーマを設定
* 必須項目はアップロードした csv 同様、ITEM_ID の他、1 つ以上のメタデータ情報

アイテムスキーマの[参考情報](https://docs.aws.amazon.com/personalize/latest/dg/schema-examples-items.html)

In [14]:
now = datetime.now()
time_str = now.strftime("-%Y-%m-%d-%H-%M-%S")

item_schema = {
    "type": "record",
    "name": "Items",
    "namespace": "com.amazonaws.personalize.schema",
    "fields": [
        {
            "name": "ITEM_ID",
            "type": "string"
        },
        {
            "name": "GENRE",
            "type": "string",
            "categorical": True
        }
    ],
    "version": "1.0"
}

create_item_schema_response = personalize.create_schema(
    name = "DEMO-movielens-item-schema" + time_str,
    schema = json.dumps(item_schema)
)

item_schema_arn = create_item_schema_response['schemaArn']
print(json.dumps(create_item_schema_response, indent=2))

{
  "schemaArn": "arn:aws:personalize:ap-northeast-1:155580384669:schema/DEMO-movielens-item-schema-2020-11-12-11-51-27",
  "ResponseMetadata": {
    "RequestId": "f819c418-c73d-44ac-9c72-8ba142f68001",
    "HTTPStatusCode": 200,
    "HTTPHeaders": {
      "content-type": "application/x-amz-json-1.1",
      "date": "Thu, 12 Nov 2020 11:51:27 GMT",
      "x-amzn-requestid": "f819c418-c73d-44ac-9c72-8ba142f68001",
      "content-length": "117",
      "connection": "keep-alive"
    },
    "RetryAttempts": 0
  }
}

#### ユーザースキーマの定義

* ユーザデータの csv に沿ったデータスキーマを設定
* 必須項目はアップロードした csv 同様、USER_ID の他、1 つ以上のメタデータ情報

ユーザスキーマの[参考情報](https://docs.aws.amazon.com/personalize/latest/dg/schema-examples-users.html)

In [15]:
now = datetime.now()
time_str = now.strftime("-%Y-%m-%d-%H-%M-%S")

user_schema = {
    "type": "record",
    "name": "Users",
    "namespace": "com.amazonaws.personalize.schema",
    "fields": [
        {
            "name": "USER_ID",
            "type": "string"
        },
        {
            "name": "AGE",
            "type": "int"
        },
        {
            "name": "GENDER",
            "type": "string",
            "categorical": True
        },
        {
            "name": "JOB",
            "type": "string",
            "categorical": True
        },
        {
            "name": "ZIP",
            "type": "string",
            "categorical": True
        }
    ],
    "version": "1.0"
}

create__user_schema_response = personalize.create_schema(
    name = "DEMO-movielens-user-schema" + time_str,
    schema = json.dumps(user_schema)
)

user_schema_arn = create__user_schema_response['schemaArn']
print(json.dumps(create__user_schema_response, indent=2))

{
  "schemaArn": "arn:aws:personalize:ap-northeast-1:155580384669:schema/DEMO-movielens-user-schema-2020-11-12-11-51-27",
  "ResponseMetadata": {
    "RequestId": "59a53d48-6268-4606-a728-c5aafc28f2eb",
    "HTTPStatusCode": 200,
    "HTTPHeaders": {
      "content-type": "application/x-amz-json-1.1",
      "date": "Thu, 12 Nov 2020 11:51:27 GMT",
      "x-amzn-requestid": "59a53d48-6268-4606-a728-c5aafc28f2eb",
      "content-length": "117",
      "connection": "keep-alive"
    },
    "RetryAttempts": 0
  }
}

##### データグループの作成
* インタラクションデータ、アイテムデータ、ユーザデータを束ねるデータグループを作成
* [参考情報](https://docs.aws.amazon.com/personalize/latest/dg/data-prep-ds-group.html)
* [create_dataset_group](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/personalize.html#Personalize.Client.create_dataset_group) メソッドはデータグループを作成するためのジョブを実行する非同期メソッド
* 完了を確認するために、別途 [describe_dataset_group](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/personalize.html#Personalize.Client.describe_dataset_group) を定期的に呼び出してジョブの実行結果を確認しにいく

ただし、 データグループ作成自体はすぐに完了（秒レベル）する

In [16]:
create_dataset_group_response = personalize.create_dataset_group(
    name = "DEMO-movielens-dataset-group" + timestamp
)

dataset_group_arn = create_dataset_group_response['datasetGroupArn']
print(json.dumps(create_dataset_group_response, indent=2))

{
  "datasetGroupArn": "arn:aws:personalize:ap-northeast-1:155580384669:dataset-group/DEMO-movielens-dataset-group-2020-11-12-11-51-18",
  "ResponseMetadata": {
    "RequestId": "52636e68-1985-4256-a787-213be409a00b",
    "HTTPStatusCode": 200,
    "HTTPHeaders": {
      "content-type": "application/x-amz-json-1.1",
      "date": "Thu, 12 Nov 2020 11:51:27 GMT",
      "x-amzn-requestid": "52636e68-1985-4256-a787-213be409a00b",
      "content-length": "132",
      "connection": "keep-alive"
    },
    "RetryAttempts": 0
  }
}

In [17]:
%%time
status = None
max_time = time.time() + 3*60*60 # 3 hours
while time.time() < max_time:
    describe_dataset_group_response = personalize.describe_dataset_group(
        datasetGroupArn = dataset_group_arn
    )
    status = describe_dataset_group_response["datasetGroup"]["status"]    
    if status == "ACTIVE" or status == "CREATE FAILED":
        print('!')
        print(f"CreateDatasetGroup: {status}")
        break
    else:
        print('.',end='')
        time.sleep(1)

...........................!
CreateDatasetGroup: ACTIVE
CPU times: user 79.7 ms, sys: 8.99 ms, total: 88.7 ms
Wall time: 27.5 s

#### インタラクションデータセット の作成
データセットグループの中にインタラクションデータセットを作成する  
必要な情報は下記 4 つ
* データセットのタイプ（この場合はインタラクションデータであることを指定）
* 親となるデータセットグループの arn
* 事前に定義したインタラクションデータのスキーマの arn
* 作成するデータセットのユニークな名前

詳細 : [create_dataset](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/personalize.html#Personalize.Client.create_dataset)

In [18]:
now = datetime.now()
time_str = now.strftime("-%Y-%m-%d-%H-%M-%S")

interaction_dataset_type = "Interactions"
create_interaction_dataset_response = personalize.create_dataset(
    datasetType = interaction_dataset_type,
    datasetGroupArn = dataset_group_arn,
    name = 'DEMO-movielens-interactions' + time_str,
    schemaArn = interaction_schema_arn
)

interaction_dataset_arn = create_interaction_dataset_response['datasetArn']
print(json.dumps(create_interaction_dataset_response, indent=2))

{
  "datasetArn": "arn:aws:personalize:ap-northeast-1:155580384669:dataset/DEMO-movielens-dataset-group-2020-11-12-11-51-18/INTERACTIONS",
  "ResponseMetadata": {
    "RequestId": "47f0fa40-54c6-4329-a303-e5ab1490c093",
    "HTTPStatusCode": 200,
    "HTTPHeaders": {
      "content-type": "application/x-amz-json-1.1",
      "date": "Thu, 12 Nov 2020 11:51:54 GMT",
      "x-amzn-requestid": "47f0fa40-54c6-4329-a303-e5ab1490c093",
      "content-length": "134",
      "connection": "keep-alive"
    },
    "RetryAttempts": 0
  }
}

#### インタラクションデータセットのインポート
作成したインタラクションデータセットにインタラクションデータをインポートする  
必須項目は下記 4 つ
* インポートジョブ名
* インタラクションデータセットの arn
* インポートするデータの S3 URI
* インポートジョブを実行するロールの arn

[create_dataset_import_job](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/personalize.html#Personalize.Client.create_dataset_import_job) はジョブを実行するだけの非同期メソッドのため、完了確認は別途行う

In [19]:
now = datetime.now()
time_str = now.strftime("-%Y-%m-%d-%H-%M-%S")

create_interaction_dataset_import_job_response = personalize.create_dataset_import_job(
    jobName = "DEMO-interaction-dataset-import-job" + time_str,
    datasetArn = interaction_dataset_arn,
    dataSource = {
        "dataLocation": "s3://{}/{}".format(bucket_name, s3_key_prefix + 'interaction.csv')
    },
    roleArn = role_arn
)

interaction_dataset_import_job_arn = create_interaction_dataset_import_job_response['datasetImportJobArn']
print(json.dumps(create_interaction_dataset_import_job_response, indent=2))

{
  "datasetImportJobArn": "arn:aws:personalize:ap-northeast-1:155580384669:dataset-import-job/DEMO-interaction-dataset-import-job-2020-11-12-11-51-55",
  "ResponseMetadata": {
    "RequestId": "b16ec3fb-a59a-4cd8-b877-6b9fea69c0e9",
    "HTTPStatusCode": 200,
    "HTTPHeaders": {
      "content-type": "application/x-amz-json-1.1",
      "date": "Thu, 12 Nov 2020 11:51:55 GMT",
      "x-amzn-requestid": "b16ec3fb-a59a-4cd8-b877-6b9fea69c0e9",
      "content-length": "148",
      "connection": "keep-alive"
    },
    "RetryAttempts": 0
  }
}

#### ユーザデータセットの作成

データセットグループの中にユーザデータセットを作成する  
必要な情報は下記 4 つ
* データセットのタイプ（この場合はユーザデータであることを指定）
* 親となるデータセットグループの arn
* 事前に定義したユーザデータのスキーマの arn
* 作成するデータセットのユニークな名前

詳細 : [create_dataset](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/personalize.html#Personalize.Client.create_dataset)

In [20]:
user_dataset_type = "Users"
create_user_dataset_response = personalize.create_dataset(
    datasetType = user_dataset_type,
    datasetGroupArn = dataset_group_arn,
    name = 'DEMO-movielens-user',
    schemaArn = user_schema_arn
)

user_dataset_arn = create_user_dataset_response['datasetArn']
print(json.dumps(create_user_dataset_response, indent=2))

{
  "datasetArn": "arn:aws:personalize:ap-northeast-1:155580384669:dataset/DEMO-movielens-dataset-group-2020-11-12-11-51-18/USERS",
  "ResponseMetadata": {
    "RequestId": "6dbc458c-01aa-49a9-b086-adec4772315f",
    "HTTPStatusCode": 200,
    "HTTPHeaders": {
      "content-type": "application/x-amz-json-1.1",
      "date": "Thu, 12 Nov 2020 11:51:54 GMT",
      "x-amzn-requestid": "6dbc458c-01aa-49a9-b086-adec4772315f",
      "content-length": "127",
      "connection": "keep-alive"
    },
    "RetryAttempts": 0
  }
}

#### ユーザーデータセットのインポート

作成したユーザデータセットにインタラクションデータをインポートする  
必須項目は下記 4 つ
* インポートジョブ名
* ユーザデータセットの arn
* インポートするデータの S3 URI
* インポートジョブを実行するロールの arn

[create_dataset_import_job](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/personalize.html#Personalize.Client.create_dataset_import_job) はジョブを実行するだけの非同期メソッドのため、完了確認は別途行う

In [21]:
now = datetime.now()
time_str = now.strftime("-%Y-%m-%d-%H-%M-%S")

create_user_dataset_import_job_response = personalize.create_dataset_import_job(
    jobName = "DEMO-user-dataset-import-job" + time_str,
    datasetArn = user_dataset_arn,
    dataSource = {
        "dataLocation": "s3://{}/{}".format(bucket_name, s3_key_prefix + 'user.csv')
    },
    roleArn = role_arn
)

user_dataset_import_job_arn = create_user_dataset_import_job_response['datasetImportJobArn']
print(json.dumps(create_user_dataset_import_job_response, indent=2))

{
  "datasetImportJobArn": "arn:aws:personalize:ap-northeast-1:155580384669:dataset-import-job/DEMO-user-dataset-import-job-2020-11-12-11-51-55",
  "ResponseMetadata": {
    "RequestId": "1626cdb5-bf60-4646-a3b0-9d0007627605",
    "HTTPStatusCode": 200,
    "HTTPHeaders": {
      "content-type": "application/x-amz-json-1.1",
      "date": "Thu, 12 Nov 2020 11:51:55 GMT",
      "x-amzn-requestid": "1626cdb5-bf60-4646-a3b0-9d0007627605",
      "content-length": "141",
      "connection": "keep-alive"
    },
    "RetryAttempts": 0
  }
}

#### アイテムデータセットの作成

データセットグループの中にアイテムデータセットを作成する  
必要な情報は下記 4 つ
* データセットのタイプ（この場合はアイテムデータであることを指定）
* 親となるデータセットグループの arn
* 事前に定義したアイテムデータのスキーマの arn
* 作成するデータセットのユニークな名前

詳細 : [create_dataset](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/personalize.html#Personalize.Client.create_dataset)

In [22]:
item_dataset_type = "Items"
create_item_dataset_response = personalize.create_dataset(
    datasetType = item_dataset_type,
    datasetGroupArn = dataset_group_arn,
    name = 'DEMO-movielens-item',
    schemaArn = item_schema_arn
)

item_dataset_arn = create_item_dataset_response['datasetArn']
print(json.dumps(create_item_dataset_response, indent=2))

{
  "datasetArn": "arn:aws:personalize:ap-northeast-1:155580384669:dataset/DEMO-movielens-dataset-group-2020-11-12-11-51-18/ITEMS",
  "ResponseMetadata": {
    "RequestId": "3ed26b52-6cc4-488b-b0d2-8107b98b9301",
    "HTTPStatusCode": 200,
    "HTTPHeaders": {
      "content-type": "application/x-amz-json-1.1",
      "date": "Thu, 12 Nov 2020 11:51:55 GMT",
      "x-amzn-requestid": "3ed26b52-6cc4-488b-b0d2-8107b98b9301",
      "content-length": "127",
      "connection": "keep-alive"
    },
    "RetryAttempts": 0
  }
}

#### アイテムデータセットのインポート

作成したアイテムデータセットにインタラクションデータをインポートする  
必須項目は下記 4 つ
* インポートジョブ名
* アイテムデータセットの arn
* インポートするデータの S3 URI
* インポートジョブを実行するロールの arn

[create_dataset_import_job](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/personalize.html#Personalize.Client.create_dataset_import_job) はジョブを実行するだけの非同期メソッドのため、完了確認は別途行う

In [23]:
now = datetime.now()
time_str = now.strftime("-%Y-%m-%d-%H-%M-%S")

create_item_dataset_import_job_response = personalize.create_dataset_import_job(
    jobName = "DEMO-item-dataset-import-job" + time_str,
    datasetArn = item_dataset_arn,
    dataSource = {
        "dataLocation": "s3://{}/{}".format(bucket_name, s3_key_prefix + 'item.csv')
    },
    roleArn = role_arn
)

item_dataset_import_job_arn = create_item_dataset_import_job_response['datasetImportJobArn']
print(json.dumps(create_item_dataset_import_job_response, indent=2))

{
  "datasetImportJobArn": "arn:aws:personalize:ap-northeast-1:155580384669:dataset-import-job/DEMO-item-dataset-import-job-2020-11-12-11-51-55",
  "ResponseMetadata": {
    "RequestId": "7729306c-27d2-4ac2-87d0-84ab7eced5b4",
    "HTTPStatusCode": 200,
    "HTTPHeaders": {
      "content-type": "application/x-amz-json-1.1",
      "date": "Thu, 12 Nov 2020 11:51:56 GMT",
      "x-amzn-requestid": "7729306c-27d2-4ac2-87d0-84ab7eced5b4",
      "content-length": "141",
      "connection": "keep-alive"
    },
    "RetryAttempts": 0
  }
}

#### インタラクションデータのインポート完了を待つ
* create_dataset_import_job はインポートジョブをキックするだけの非同期メソッド
* 終わるまでソリューションのバージョンの作成が出来ないため、終了を確認する処理を行う
* describe_dataset_import_job でジョブのステータスが確認できるので、 ACTIVE になるまで待つ
* [describe_dataset_import_job](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/personalize.html#Personalize.Client.describe_dataset_import_job) に必要な引数は データセットインポートジョブの arn のみ
* 下記セルはインタラクションデータセットのインポートジョブの完了確認だが、アイテムもユーザも同様

In [24]:
%%time

status = None
max_time = time.time() + 3*60*60 # 3 hours
while time.time() < max_time:
    describe_dataset_import_job_response = personalize.describe_dataset_import_job(
        datasetImportJobArn = interaction_dataset_import_job_arn
    )
    
    dataset_import_job = describe_dataset_import_job_response["datasetImportJob"]
    status = dataset_import_job["status"]
    
    if status == "ACTIVE" or status == "CREATE FAILED":
        print('!')
        print(f"LatestDatasetImportJobRun: {status}")
        break
    else:
        print('.',end='')
        
    time.sleep(5)

...........................................................................................................................................................!
LatestDatasetImportJobRun: ACTIVE
CPU times: user 464 ms, sys: 43.4 ms, total: 507 ms
Wall time: 12min 58s

#### ユーザーデータのインポート完了を待つ

In [25]:
%%time

status = None
max_time = time.time() + 3*60*60 # 3 hours
while time.time() < max_time:
    describe_dataset_import_job_response = personalize.describe_dataset_import_job(
        datasetImportJobArn = user_dataset_import_job_arn
    )
    
    dataset_import_job = describe_dataset_import_job_response["datasetImportJob"]
    status = dataset_import_job["status"]
    
    if status == "ACTIVE" or status == "CREATE FAILED":
        print('!')
        print(f"LatestDatasetImportJobRun: {status}")
        break
    else:
        print('.',end='')
        
    time.sleep(5)

............!
LatestDatasetImportJobRun: ACTIVE
CPU times: user 39.6 ms, sys: 2.16 ms, total: 41.8 ms
Wall time: 1min

#### アイテムデータのインポート完了を待つ

In [26]:
%%time

status = None
max_time = time.time() + 3*60*60 # 3 hours
while time.time() < max_time:
    describe_dataset_import_job_response = personalize.describe_dataset_import_job(
        datasetImportJobArn = item_dataset_import_job_arn
    )
    
    dataset_import_job = describe_dataset_import_job_response["datasetImportJob"]
    status = dataset_import_job["status"]
    
    if status == "ACTIVE" or status == "CREATE FAILED":
        print('!')
        print(f"LatestDatasetImportJobRun: {status}")
        break
    else:
        print('.',end='')
        
    time.sleep(5)

....!
LatestDatasetImportJobRun: ACTIVE
CPU times: user 15.7 ms, sys: 341 µs, total: 16 ms
Wall time: 20.1 s

### ソリューションの作成
* 各ソリューションのトレーニング完了までには一定時間掛かるため、レシピ毎にトレーニングジョブを並列で起動し、後続のステップですべてのトレーニングジョブが完了するのを待つ
* ソリューションを作成するにあたって、各ソリューションに使うレシピの arn が必要なので最初にレシピの arn を取得する

In [27]:
list_recipes_response = personalize.list_recipes()
recipe_arns = {}
for recipe in list_recipes_response['recipes']:
    recipe_arns[recipe['recipeArn'].split('/')[-1]] = recipe['recipeArn']
for key in recipe_arns.keys():
    print(key + ' -> ' + recipe_arns[key])

aws-hrnn -> arn:aws:personalize:::recipe/aws-hrnn
aws-hrnn-coldstart -> arn:aws:personalize:::recipe/aws-hrnn-coldstart
aws-hrnn-metadata -> arn:aws:personalize:::recipe/aws-hrnn-metadata
aws-personalized-ranking -> arn:aws:personalize:::recipe/aws-personalized-ranking
aws-popularity-count -> arn:aws:personalize:::recipe/aws-popularity-count
aws-sims -> arn:aws:personalize:::recipe/aws-sims
aws-user-personalization -> arn:aws:personalize:::recipe/aws-user-personalization

#### ソリューションの作成（user-personalization）
* user-personalization レシピを使ったソリューションを [create_solution](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/personalize.html#Personalize.Client.create_solution)メソッドを使って作成する
* create_solution メソッドの必須項目は下記の通り
  * ソリューション のユニークな名前
  * データセットグループの arn
  * AutoMLを利用しないときはレシピの arn
* performHPO は現状デフォルトで False だが、念の為明示的に False を指定
  * HPO は時間がかかるため、本ハンズオンでは使用しない
* この段階ではあくまでソリューションの箱を作るだけで実際に学習を開始するのは次の処理

In [28]:
now = datetime.now()
time_str = now.strftime("-%Y-%m-%d-%H-%M-%S")

user_personalization_create_solution_response = personalize.create_solution(
    name = "DEMO-movielens-user-personalization" + time_str,
    datasetGroupArn = dataset_group_arn,
    recipeArn = recipe_arns["aws-user-personalization"],
    performHPO = False
)

user_personalization_solution_arn = user_personalization_create_solution_response['solutionArn']
print(json.dumps(user_personalization_create_solution_response, indent=2))

{
  "solutionArn": "arn:aws:personalize:ap-northeast-1:155580384669:solution/DEMO-movielens-user-personalization-2020-11-12-12-06-14",
  "ResponseMetadata": {
    "RequestId": "7534fd8e-fadb-483b-b7cc-5269944f4763",
    "HTTPStatusCode": 200,
    "HTTPHeaders": {
      "content-type": "application/x-amz-json-1.1",
      "date": "Thu, 12 Nov 2020 12:06:14 GMT",
      "x-amzn-requestid": "7534fd8e-fadb-483b-b7cc-5269944f4763",
      "content-length": "130",
      "connection": "keep-alive"
    },
    "RetryAttempts": 0
  }
}

#### ソリューションのバージョンの作成(user-personalization)
* **時間のかかる処理をキックします**
* 非同期メソッドの実行なのでバージョン作成の完了確認は別途実行
* [create_solution_verion](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/personalize.html#Personalize.Client.create_solution_version) の実行には 作成したソリューション の arn を指定するだけでよい

In [29]:
user_personalization_create_solution_version_response = personalize.create_solution_version(
    solutionArn=user_personalization_solution_arn
)

In [30]:
user_personalization_solution_version_arn = user_personalization_create_solution_version_response['solutionVersionArn']
print(json.dumps(user_personalization_create_solution_version_response, indent=2))

{
  "solutionVersionArn": "arn:aws:personalize:ap-northeast-1:155580384669:solution/DEMO-movielens-user-personalization-2020-11-12-12-06-14/cdd65f51",
  "ResponseMetadata": {
    "RequestId": "6a9cb8cd-0bdd-4e59-a536-ca7886cbcd5e",
    "HTTPStatusCode": 200,
    "HTTPHeaders": {
      "content-type": "application/x-amz-json-1.1",
      "date": "Thu, 12 Nov 2020 12:06:14 GMT",
      "x-amzn-requestid": "6a9cb8cd-0bdd-4e59-a536-ca7886cbcd5e",
      "content-length": "146",
      "connection": "keep-alive"
    },
    "RetryAttempts": 0
  }
}

#### ソリューションの作成（personalized-ranking）

In [31]:
now = datetime.now()
time_str = now.strftime("-%Y-%m-%d-%H-%M-%S")

personalized_ranking_create_solution_response = personalize.create_solution(
    name = "DEMO-movielens-personalized-ranking" + time_str,
    datasetGroupArn = dataset_group_arn,
    recipeArn = recipe_arns["aws-personalized-ranking"],
    performHPO = False
)

personalized_ranking_solution_arn = personalized_ranking_create_solution_response['solutionArn']
print(json.dumps(personalized_ranking_create_solution_response, indent=2))

{
  "solutionArn": "arn:aws:personalize:ap-northeast-1:155580384669:solution/DEMO-movielens-personalized-ranking-2020-11-12-12-06-15",
  "ResponseMetadata": {
    "RequestId": "4d84dabe-5823-4ca3-b053-fc2f65a48594",
    "HTTPStatusCode": 200,
    "HTTPHeaders": {
      "content-type": "application/x-amz-json-1.1",
      "date": "Thu, 12 Nov 2020 12:06:15 GMT",
      "x-amzn-requestid": "4d84dabe-5823-4ca3-b053-fc2f65a48594",
      "content-length": "130",
      "connection": "keep-alive"
    },
    "RetryAttempts": 0
  }
}

In [32]:
personalized_ranking_create_solution_version_response = personalize.create_solution_version(solutionArn=personalized_ranking_solution_arn)

In [33]:
personalized_ranking_solution_version_arn = personalized_ranking_create_solution_version_response['solutionVersionArn']
print(json.dumps(personalized_ranking_create_solution_version_response, indent=2))

{
  "solutionVersionArn": "arn:aws:personalize:ap-northeast-1:155580384669:solution/DEMO-movielens-personalized-ranking-2020-11-12-12-06-15/a910858f",
  "ResponseMetadata": {
    "RequestId": "33e40067-8755-4981-b27a-1e8a804341cb",
    "HTTPStatusCode": 200,
    "HTTPHeaders": {
      "content-type": "application/x-amz-json-1.1",
      "date": "Thu, 12 Nov 2020 12:06:14 GMT",
      "x-amzn-requestid": "33e40067-8755-4981-b27a-1e8a804341cb",
      "content-length": "146",
      "connection": "keep-alive"
    },
    "RetryAttempts": 0
  }
}

#### ソリューションの作成（sims）

In [34]:
now = datetime.now()
time_str = now.strftime("-%Y-%m-%d-%H-%M-%S")

sims_create_solution_response = personalize.create_solution(
    name = "DEMO-movielens-sims" + time_str,
    datasetGroupArn = dataset_group_arn,
    recipeArn = recipe_arns["aws-sims"],
    performHPO = False
)

sims_solution_arn = sims_create_solution_response['solutionArn']
print(json.dumps(sims_create_solution_response, indent=2))

{
  "solutionArn": "arn:aws:personalize:ap-northeast-1:155580384669:solution/DEMO-movielens-sims-2020-11-12-12-06-15",
  "ResponseMetadata": {
    "RequestId": "b3caae6b-f16d-4007-8d10-fac86f086e6c",
    "HTTPStatusCode": 200,
    "HTTPHeaders": {
      "content-type": "application/x-amz-json-1.1",
      "date": "Thu, 12 Nov 2020 12:06:15 GMT",
      "x-amzn-requestid": "b3caae6b-f16d-4007-8d10-fac86f086e6c",
      "content-length": "114",
      "connection": "keep-alive"
    },
    "RetryAttempts": 0
  }
}

In [35]:
sims_create_solution_version_response = personalize.create_solution_version(solutionArn=sims_solution_arn)

In [36]:
sims_solution_version_arn = sims_create_solution_version_response['solutionVersionArn']
print(json.dumps(sims_create_solution_version_response, indent=2))

{
  "solutionVersionArn": "arn:aws:personalize:ap-northeast-1:155580384669:solution/DEMO-movielens-sims-2020-11-12-12-06-15/f869bd37",
  "ResponseMetadata": {
    "RequestId": "a87909ea-4c5c-4dc4-b306-9e4e117ee561",
    "HTTPStatusCode": 200,
    "HTTPHeaders": {
      "content-type": "application/x-amz-json-1.1",
      "date": "Thu, 12 Nov 2020 12:06:15 GMT",
      "x-amzn-requestid": "a87909ea-4c5c-4dc4-b306-9e4e117ee561",
      "content-length": "130",
      "connection": "keep-alive"
    },
    "RetryAttempts": 0
  }
}

#### user-personalizationレシピのトレーニング完了を待つ
* ソリューションのバージョン作成は非同期メソッドのため完了を確認する処理を別途行う
* [describe_solution_version](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/personalize.html#Personalize.Client.describe_solution_version) でステータスを取得可能
* 引数は ソリューションバージョンの arn のみ

**40 分くらい待ちます**

In [ ]:
%%time

status = None
max_time = time.time() + 3*60*60 # 3 hours
while time.time() < max_time:
    describe_solution_version_response = personalize.describe_solution_version(
        solutionVersionArn = user_personalization_solution_version_arn
    )
    status = describe_solution_version_response["solutionVersion"]["status"]
    
    if status == "ACTIVE" or status == "CREATE FAILED":
        print('!')
        print(f"LatestDatasetImportJobRun: {status}")
        break
    else:
        print('.',end='')
        
    time.sleep(5)

.......................................................................................................................................................................................................................................................................................................................................................................................!
LatestDatasetImportJobRun: ACTIVE
CPU times: user 1.44 s, sys: 105 ms, total: 1.54 s
Wall time: 39min 38s

#### personalized-rankingレシピのトレーニング完了を待つ

In [ ]:
%%time

status = None
max_time = time.time() + 3*60*60 # 3 hours
while time.time() < max_time:
    describe_solution_version_response = personalize.describe_solution_version(
        solutionVersionArn = personalized_ranking_solution_version_arn
    )
    status = describe_solution_version_response["solutionVersion"]["status"]
    
    if status == "ACTIVE" or status == "CREATE FAILED":
        print('!')
        print("LatestDatasetImportJobRun: {}".format(status))
        break
    else:
        print('.',end='')
        
    time.sleep(5)

.!
LatestDatasetImportJobRun: ACTIVE
CPU times: user 6.93 ms, sys: 0 ns, total: 6.93 ms
Wall time: 5.05 s

#### simsレシピのトレーニング完了を待つ

In [ ]:
%%time

status = None
max_time = time.time() + 3*60*60 # 3 hours
while time.time() < max_time:
    describe_solution_version_response = personalize.describe_solution_version(
        solutionVersionArn = sims_solution_version_arn
    )
    status = describe_solution_version_response["solutionVersion"]["status"]
    
    if status == "ACTIVE" or status == "CREATE FAILED":
        print('!')
        print("LatestDatasetImportJobRun: {}".format(status))
        break
    else:
        print('.',end='')
        
    time.sleep(5)

!
LatestDatasetImportJobRun: ACTIVE
CPU times: user 3.09 ms, sys: 216 µs, total: 3.3 ms
Wall time: 17.2 ms

#### ソリューションメトリックの取得（user-personalization）
* 学習したソリューションのバージョンのメトリックを [get_solution_metrics](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/personalize.html#Personalize.Client.get_solution_metrics) で取得することが可能
* 引数は ソリューションバージョンの arn のみ

In [ ]:
get_solution_metrics_response = personalize.get_solution_metrics(
    solutionVersionArn = user_personalization_solution_version_arn
)

print(json.dumps(get_solution_metrics_response, indent=2))

{
  "solutionVersionArn": "arn:aws:personalize:ap-northeast-1:155580384669:solution/DEMO-movielens-user-personalization-2020-11-12-12-06-14/cdd65f51",
  "metrics": {
    "coverage": 0.1396,
    "mean_reciprocal_rank_at_25": 0.0,
    "normalized_discounted_cumulative_gain_at_10": 0.0,
    "normalized_discounted_cumulative_gain_at_25": 0.0,
    "normalized_discounted_cumulative_gain_at_5": 0.0,
    "precision_at_10": 0.0,
    "precision_at_25": 0.0,
    "precision_at_5": 0.0
  },
  "ResponseMetadata": {
    "RequestId": "4817f420-7283-44ce-979e-c3d6c5e79c1e",
    "HTTPStatusCode": 200,
    "HTTPHeaders": {
      "content-type": "application/x-amz-json-1.1",
      "date": "Thu, 12 Nov 2020 12:45:58 GMT",
      "x-amzn-requestid": "4817f420-7283-44ce-979e-c3d6c5e79c1e",
      "content-length": "423",
      "connection": "keep-alive"
    },
    "RetryAttempts": 0
  }
}

#### ソリューションメトリックの取得（personalized-ranking）

In [ ]:
get_solution_metrics_response = personalize.get_solution_metrics(
    solutionVersionArn = personalized_ranking_solution_version_arn
)

print(json.dumps(get_solution_metrics_response, indent=2))

{
  "solutionVersionArn": "arn:aws:personalize:ap-northeast-1:155580384669:solution/DEMO-movielens-personalized-ranking-2020-11-12-12-06-15/a910858f",
  "metrics": {
    "coverage": 0.023,
    "mean_reciprocal_rank_at_25": 0.0152,
    "normalized_discounted_cumulative_gain_at_10": 0.0222,
    "normalized_discounted_cumulative_gain_at_25": 0.0421,
    "normalized_discounted_cumulative_gain_at_5": 0.0132,
    "precision_at_10": 0.0039,
    "precision_at_25": 0.0047,
    "precision_at_5": 0.0026
  },
  "ResponseMetadata": {
    "RequestId": "8af27811-ba97-4724-b246-3ca74e0e465c",
    "HTTPStatusCode": 200,
    "HTTPHeaders": {
      "content-type": "application/x-amz-json-1.1",
      "date": "Thu, 12 Nov 2020 12:45:58 GMT",
      "x-amzn-requestid": "8af27811-ba97-4724-b246-3ca74e0e465c",
      "content-length": "443",
      "connection": "keep-alive"
    },
    "RetryAttempts": 0
  }
}

#### ソリューションメトリックの取得（sims）

In [ ]:
get_solution_metrics_response = personalize.get_solution_metrics(
    solutionVersionArn = sims_solution_version_arn
)

print(json.dumps(get_solution_metrics_response, indent=2))

{
  "solutionVersionArn": "arn:aws:personalize:ap-northeast-1:155580384669:solution/DEMO-movielens-sims-2020-11-12-12-06-15/f869bd37",
  "metrics": {
    "coverage": 0.3143,
    "mean_reciprocal_rank_at_25": 0.033,
    "normalized_discounted_cumulative_gain_at_10": 0.0436,
    "normalized_discounted_cumulative_gain_at_25": 0.0647,
    "normalized_discounted_cumulative_gain_at_5": 0.0398,
    "precision_at_10": 0.0061,
    "precision_at_25": 0.0059,
    "precision_at_5": 0.0098
  },
  "ResponseMetadata": {
    "RequestId": "3d40575b-709c-4445-a015-99c052b359ee",
    "HTTPStatusCode": 200,
    "HTTPHeaders": {
      "content-type": "application/x-amz-json-1.1",
      "date": "Thu, 12 Nov 2020 12:45:59 GMT",
      "x-amzn-requestid": "3d40575b-709c-4445-a015-99c052b359ee",
      "content-length": "427",
      "connection": "keep-alive"
    },
    "RetryAttempts": 0
  }
}

### キャンペーンの作成
* 各キャンペーン作成完了までには一定時間掛かるため、キャンペーンの作成をを並列実行し、後続のステップですべてのキャンペーン作成完了を待つ
* キャンペーンを作成することでレコメンデーションができるようになる

#### キャンペーンの作成（user-personalization）
* キャンペーンの作成は [create_campaign](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/personalize.html#Personalize.Client.create_campaign) メソッドを使う(非同期メソッドのため完了は別途確認)
* 必須項目は 3 つ
  * キャンペーンのユニークな名前
  * 適用するソリューションバージョンの arn
  * 最低限確保する TPS ( 1 秒あたりにさばけるトランザクション量）

In [ ]:
now = datetime.now()
time_str = now.strftime("-%Y-%m-%d-%H-%M-%S")

create_user_personalization_campaign_response = personalize.create_campaign(
    name = "DEMO-campaign-user-personalization" + time_str,
    solutionVersionArn = user_personalization_solution_version_arn,
    minProvisionedTPS = 1,
    campaignConfig =  { 
      "itemExplorationConfig": { 
         "explorationWeight" : "0.3",
         "explorationItemAgeCutOff" : "30.0",
      }
   },
)

user_personalization_campaign_arn = create_user_personalization_campaign_response['campaignArn']
print(json.dumps(create_user_personalization_campaign_response, indent=2))

{
  "campaignArn": "arn:aws:personalize:ap-northeast-1:155580384669:campaign/DEMO-campaign-user-personalization-2020-11-12-12-45-59",
  "ResponseMetadata": {
    "RequestId": "7e295445-574a-40ba-a194-904241e2d191",
    "HTTPStatusCode": 200,
    "HTTPHeaders": {
      "content-type": "application/x-amz-json-1.1",
      "date": "Thu, 12 Nov 2020 12:45:59 GMT",
      "x-amzn-requestid": "7e295445-574a-40ba-a194-904241e2d191",
      "content-length": "129",
      "connection": "keep-alive"
    },
    "RetryAttempts": 0
  }
}

#### キャンペーンの作成（sims）

In [ ]:
now = datetime.now()
time_str = now.strftime("-%Y-%m-%d-%H-%M-%S")

create_sims_campaign_response = personalize.create_campaign(
    name = "DEMO-campaign-sims" + time_str,
    solutionVersionArn = sims_solution_version_arn,
    minProvisionedTPS = 1
)

sims_campaign_arn = create_sims_campaign_response['campaignArn']
print(json.dumps(create_sims_campaign_response, indent=2))

{
  "campaignArn": "arn:aws:personalize:ap-northeast-1:155580384669:campaign/DEMO-campaign-sims-2020-11-12-12-45-59",
  "ResponseMetadata": {
    "RequestId": "7bce9b7c-de36-428e-97c5-5e844a21e769",
    "HTTPStatusCode": 200,
    "HTTPHeaders": {
      "content-type": "application/x-amz-json-1.1",
      "date": "Thu, 12 Nov 2020 12:45:59 GMT",
      "x-amzn-requestid": "7bce9b7c-de36-428e-97c5-5e844a21e769",
      "content-length": "113",
      "connection": "keep-alive"
    },
    "RetryAttempts": 0
  }
}

#### キャンペーンの作成（personalized-ranking）

In [ ]:
now = datetime.now()
time_str = now.strftime("-%Y-%m-%d-%H-%M-%S")

create_personalized_ranking_campaign_response = personalize.create_campaign(
    name = "DEMO-campaign-personalized-ranking" + time_str,
    solutionVersionArn = personalized_ranking_solution_version_arn,
    minProvisionedTPS = 1
)

personalized_ranking_campaign_arn = create_personalized_ranking_campaign_response['campaignArn']
print(json.dumps(create_personalized_ranking_campaign_response, indent=2))

{
  "campaignArn": "arn:aws:personalize:ap-northeast-1:155580384669:campaign/DEMO-campaign-personalized-ranking-2020-11-12-12-45-59",
  "ResponseMetadata": {
    "RequestId": "ad377194-8c5c-4f87-9e88-e3088145ef16",
    "HTTPStatusCode": 200,
    "HTTPHeaders": {
      "content-type": "application/x-amz-json-1.1",
      "date": "Thu, 12 Nov 2020 12:45:59 GMT",
      "x-amzn-requestid": "ad377194-8c5c-4f87-9e88-e3088145ef16",
      "content-length": "129",
      "connection": "keep-alive"
    },
    "RetryAttempts": 0
  }
}

#### キャンペーンの作成完了待ち（user-personalization）
* キャンペーン作成のステータスは [describe_campaign](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/personalize.html#Personalize.Client.describe_campaign) で取得できる
* キャンペーンの arn を指定するのみ
* キャンペーンの作成が完了するまで 10 分程度かかる

In [ ]:
%%time

status = None
max_time = time.time() + 3*60*60 # 3 hours
while time.time() < max_time:
    describe_campaign_response = personalize.describe_campaign(
        campaignArn = user_personalization_campaign_arn
    )
    status = describe_campaign_response["campaign"]["status"]
    
    if status == "ACTIVE" or status == "CREATE FAILED":
        print('!')
        print(f"LatestDatasetImportJobRun: {status}")
        break
    else:
        print('.',end='')
        
    time.sleep(5)

.............................................................................................................!
LatestDatasetImportJobRun: ACTIVE
CPU times: user 317 ms, sys: 47.3 ms, total: 364 ms
Wall time: 9min 8s

#### キャンペーンの作成完了待ち（sims）

In [ ]:
%%time

status = None
max_time = time.time() + 3*60*60 # 3 hours
while time.time() < max_time:
    describe_campaign_response = personalize.describe_campaign(
        campaignArn = sims_campaign_arn
    )
    status = describe_campaign_response["campaign"]["status"]
    
    if status == "ACTIVE" or status == "CREATE FAILED":
        print('!')
        print("LatestDatasetImportJobRun: {}".format(status))
        break
    else:
        print('.',end='')
        
    time.sleep(5)

!
LatestDatasetImportJobRun: ACTIVE
CPU times: user 3.12 ms, sys: 0 ns, total: 3.12 ms
Wall time: 27.7 ms

#### キャンペーンの作成完了待ち（personalizad-ranking）

In [ ]:
%%time

status = None
max_time = time.time() + 3*60*60 # 3 hours
while time.time() < max_time:
    describe_campaign_response = personalize.describe_campaign(
        campaignArn = personalized_ranking_campaign_arn
    )
    status = describe_campaign_response["campaign"]["status"]
    
    if status == "ACTIVE" or status == "CREATE FAILED":
        print('!')
        print("LatestDatasetImportJobRun: {}".format(status))
        break
    else:
        print('.',end='')
        
    time.sleep(5)

!
LatestDatasetImportJobRun: ACTIVE
CPU times: user 2.87 ms, sys: 170 µs, total: 3.04 ms
Wall time: 36.9 ms

### APIの呼び出し
* ここからは、実際にレコメンデーションをする
* レコメンデーションは boto3 の personalize-runtime を用いる

In [ ]:
# 事前にアイテムとユーザのデータを読み込む
item_data = pd.read_csv('./ml-100k/u.item', sep='|', encoding='latin-1', header=None)
item_data = item_data.drop(columns=3)
item_data = item_data.rename(columns={0:'ITEM_ID', 1:'TITLE', 2:'RELEASE', 4:'IMDB_URL', 5:'unknown', 6:'Action', 7:'Adventure', 8:'Animation', 9:"Children's", 10:'Comedy', 11:'Crime', 12:'Documentary', 13:'Drama', 14:'Fantasy', 15:'Film-Noir', 16:'Horror', 17:'Musical', 18:'Mystery', 19:'Romance', 20:'Sci-Fi', 21:'Thriller', 22:'War', 23:'Western'})
item_data.head()

,ITEM_ID,TITLE,RELEASE,IMDB_URL,unknown,Action,Adventure,Animation,Children's,Comedy,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),01-Jan-1995,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [ ]:
user_data = pd.read_csv('./ml-100k/u.user', sep='|', names=['USER_ID', 'AGE', 'GENDER', 'JOB', 'ZIP'])
user_data.head(11)

    USER_ID  AGE GENDER            JOB    ZIP
0         1   24      M     technician  85711
1         2   53      F          other  94043
2         3   23      M         writer  32067
3         4   24      M     technician  43537
4         5   33      F          other  15213
5         6   42      M      executive  98101
6         7   57      M  administrator  91344
7         8   36      M  administrator  05201
8         9   29      M        student  01002
9        10   53      M         lawyer  90703
10       11   39      F          other  30329

#### ユーザー向けレコメンデーションAPIの呼び出し
* ユーザ ID が 10 の人には何をレコメンデーションするべきか、というサンプル
* [get_recommendations](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/personalize-runtime.html#PersonalizeRuntime.Client.get_recommendations) メソッドに、 USER-PERSONALIZATION レシピを使用しているキャンペーンの arn と、 ユーザ ID を指定する
* レコメンデーションを返してくれるアイテム数はデフォルトで 25 だが、最大で 500 まで増やせる

In [ ]:
get_recommendations_response = personalize_runtime.get_recommendations(
    campaignArn = user_personalization_campaign_arn,
    userId = '10'
)

item_list = get_recommendations_response['itemList']
title_list = [item_data.loc[item_data['ITEM_ID'] == np.int(item['itemId'])].values[0][1] for item in item_list]

print("Recommendations: {}".format(json.dumps(title_list, indent=2)))

Recommendations: [
  "Bent (1997)",
  "Angel on My Shoulder (1946)",
  "Congo (1995)",
  "Jason's Lyric (1994)",
  "Beyond Bedlam (1993)",
  "Farinelli: il castrato (1994)",
  "Heaven & Earth (1993)",
  "Big Bang Theory, The (1994)",
  "Newton Boys, The (1998)",
  "MURDER and murder (1996)",
  "Clean Slate (Coup de Torchon) (1981)",
  "Normal Life (1996)",
  "Gang Related (1997)",
  "Outlaw, The (1943)",
  "All Dogs Go to Heaven 2 (1996)",
  "Guilty as Sin (1993)",
  "Free Willy (1993)",
  "Lashou shentan (1992)",
  "City of Industry (1997)",
  "Johnny 100 Pesos (1993)",
  "Spanish Prisoner, The (1997)",
  "Time Tracers (1995)",
  "Simple Twist of Fate, A (1994)",
  "Somebody to Love (1994)",
  "Robert A. Heinlein's The Puppet Masters (1994)"
]

#### 類似アイテムAPIの呼び出し

* [get_recommendations](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/personalize-runtime.html#PersonalizeRuntime.Client.get_recommendations) メソッドを sims のキャンペーンの arn を指定し、類似アイテムの元となる itemId を指定して呼び出す

In [ ]:
get_recommendations_response = personalize_runtime.get_recommendations(
    campaignArn = sims_campaign_arn,
    itemId = '30' # ItemId が 30 の商品の類似商品を出す
)

item_list = get_recommendations_response['itemList']
title_list = [item_data.loc[item_data['ITEM_ID'] == np.int(item['itemId'])].values[0][1] for item in item_list]

print(item_data.loc[item_data['ITEM_ID'] == 30].TITLE.values[0])
print("Recommendations: {}".format(json.dumps(title_list, indent=2)))

Belle de jour (1967)
Recommendations: [
  "Star Wars (1977)",
  "Return of the Jedi (1983)",
  "Fargo (1996)",
  "Godfather, The (1972)",
  "Silence of the Lambs, The (1991)",
  "Raiders of the Lost Ark (1981)",
  "Contact (1997)",
  "Toy Story (1995)",
  "Empire Strikes Back, The (1980)",
  "Titanic (1997)",
  "Rock, The (1996)",
  "Terminator, The (1984)",
  "English Patient, The (1996)",
  "Shawshank Redemption, The (1994)",
  "Air Force One (1997)",
  "Jerry Maguire (1996)",
  "Forrest Gump (1994)",
  "Back to the Future (1985)",
  "One Flew Over the Cuckoo's Nest (1975)",
  "L.A. Confidential (1997)",
  "Star Trek: First Contact (1996)",
  "Pulp Fiction (1994)",
  "Indiana Jones and the Last Crusade (1989)",
  "Dead Man Walking (1995)",
  "Monty Python and the Holy Grail (1974)"
]

#### Personalized Ranking APIの呼び出し
* 勧めたい商品が複数あったときにどの優先順位で勧めればよいかを知る
* [get_personalized_ranking](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/personalize-runtime.html#PersonalizeRuntime.Client.get_personalized_ranking) を利用する
* キャンペーンの arn, ユーザ ID, 優先順位を知りたいアイテムのリストを引数に呼び出す

In [ ]:
input_item_list = [str(i) for i in range(1,11)]

get_personalized_ranking_response = personalize_runtime.get_personalized_ranking(
    campaignArn = personalized_ranking_campaign_arn,
    userId = '20', # UserId が 20 の人にとってのランキング
    inputList = input_item_list
)

item_list = get_personalized_ranking_response['personalizedRanking']
item_id_list = [item['itemId'] for item in item_list]

print("PersonalizedRanking: {}".format(json.dumps(item_id_list, indent=2)))

PersonalizedRanking: [
  "1",
  "9",
  "8",
  "7",
  "4",
  "10",
  "5",
  "2",
  "6",
  "3"
]

### リアルタイムイベント処理
#### EventTrackerの作成
* リアルタイムのお客様のアクションを取り込んでレコメンデーションを行うための、EventTracker を作成する
* [create_event_tracker](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/personalize.html#Personalize.Client.create_event_tracker) メソッドで作成できる
* データセットグループの arn と、ユニークな名前を指定して実行する
* 30 秒程度で完了する

In [ ]:
create_event_tracker_response = personalize.create_event_tracker(
    datasetGroupArn = dataset_group_arn,
    name = 'DEMO-event-tracker'
)

print(json.dumps(create_event_tracker_response, indent=2))

{
  "eventTrackerArn": "arn:aws:personalize:ap-northeast-1:155580384669:event-tracker/1854a44b",
  "trackingId": "2c28d966-3e83-4fe4-a9fb-2b3c85dd9f79",
  "ResponseMetadata": {
    "RequestId": "d4206c1a-61e0-46dc-8d6c-de51fbef15dc",
    "HTTPStatusCode": 200,
    "HTTPHeaders": {
      "content-type": "application/x-amz-json-1.1",
      "date": "Thu, 12 Nov 2020 12:55:08 GMT",
      "x-amzn-requestid": "d4206c1a-61e0-46dc-8d6c-de51fbef15dc",
      "content-length": "144",
      "connection": "keep-alive"
    },
    "RetryAttempts": 0
  }
}

In [ ]:
event_tracker_arn = create_event_tracker_response['eventTrackerArn']

In [ ]:
%%time

status = None
max_time = time.time() + 3*60*60 # 3 hours
while time.time() < max_time:
    describe_event_tracker_response = personalize.describe_event_tracker(
        eventTrackerArn = event_tracker_arn
    )
    status = describe_event_tracker_response["eventTracker"]["status"]
    
    if status == "ACTIVE" or status == "CREATE FAILED":
        print('!')
        print(f'status:{status}')
        break
    print('.',end = '')
    time.sleep(5)

......!
status:ACTIVE
CPU times: user 20.7 ms, sys: 1.71 ms, total: 22.4 ms
Wall time: 30.1 s

#### レコメンデーションのリストを取得
* 比較のため、まずは Event Tracker を使わずにレコメンデーションする

In [ ]:
get_recommendations_response = personalize_runtime.get_recommendations(
    campaignArn = user_personalization_campaign_arn,
    userId = '10'
)

item_list = get_recommendations_response['itemList']
title_list = [item_data.loc[item_data['ITEM_ID'] == np.int(item['itemId'])].values[0][1] for item in item_list]

print("Recommendations: {}".format(json.dumps(title_list, indent=2)))

Recommendations: [
  "Bent (1997)",
  "Angel on My Shoulder (1946)",
  "Congo (1995)",
  "Jason's Lyric (1994)",
  "Beyond Bedlam (1993)",
  "Farinelli: il castrato (1994)",
  "Heaven & Earth (1993)",
  "Big Bang Theory, The (1994)",
  "Newton Boys, The (1998)",
  "MURDER and murder (1996)",
  "Clean Slate (Coup de Torchon) (1981)",
  "Normal Life (1996)",
  "Gang Related (1997)",
  "Outlaw, The (1943)",
  "All Dogs Go to Heaven 2 (1996)",
  "Guilty as Sin (1993)",
  "Free Willy (1993)",
  "Lashou shentan (1992)",
  "City of Industry (1997)",
  "Johnny 100 Pesos (1993)",
  "Spanish Prisoner, The (1997)",
  "Time Tracers (1995)",
  "Simple Twist of Fate, A (1994)",
  "Somebody to Love (1994)",
  "Robert A. Heinlein's The Puppet Masters (1994)"
]

#### リアルタイムイベントを Feed

In [ ]:
import uuid
from datetime import datetime

now = datetime.now()

sentAt = str(now.timestamp())
int(now.timestamp())

session_id = str(uuid.uuid4())
event_id = str(uuid.uuid4())

In [ ]:
trackingId = create_event_tracker_response['trackingId']

In [ ]:
personalize_events.put_events(
    trackingId = trackingId,
    userId = '10',
    sessionId = session_id,
    eventList = [
      {
          "eventId": event_id,
          "sentAt": int(now.timestamp()),
          "eventType": "RATING",
          "properties": json.dumps(
            {
                'itemId': '215',
                'eventValue': 5
            })
      }
    ]
)

{'ResponseMetadata': {'RequestId': 'fa52c998-2ffb-41e9-9350-acaf5fc3c71b',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'content-type': 'application/json',
   'date': 'Thu, 12 Nov 2020 12:55:38 GMT',
   'x-amzn-requestid': 'fa52c998-2ffb-41e9-9350-acaf5fc3c71b',
   'content-length': '0',
   'connection': 'keep-alive'},
  'RetryAttempts': 0}}

#### レコメンデーションのリストを再取得

In [ ]:
get_recommendations_response = personalize_runtime.get_recommendations(
    campaignArn = user_personalization_campaign_arn,
    userId = '10'
)

item_list = get_recommendations_response['itemList']
title_list = [item_data.loc[item_data['ITEM_ID'] == np.int(item['itemId'])].values[0][1] for item in item_list]

print("Recommendations: {}".format(json.dumps(title_list, indent=2)))

Recommendations: [
  "Bent (1997)",
  "Angel on My Shoulder (1946)",
  "Congo (1995)",
  "Jason's Lyric (1994)",
  "Beyond Bedlam (1993)",
  "Farinelli: il castrato (1994)",
  "Heaven & Earth (1993)",
  "Big Bang Theory, The (1994)",
  "Newton Boys, The (1998)",
  "MURDER and murder (1996)",
  "Clean Slate (Coup de Torchon) (1981)",
  "Normal Life (1996)",
  "Gang Related (1997)",
  "Outlaw, The (1943)",
  "All Dogs Go to Heaven 2 (1996)",
  "Guilty as Sin (1993)",
  "Free Willy (1993)",
  "Lashou shentan (1992)",
  "City of Industry (1997)",
  "Johnny 100 Pesos (1993)",
  "Spanish Prisoner, The (1997)",
  "Time Tracers (1995)",
  "Simple Twist of Fate, A (1994)",
  "Somebody to Love (1994)",
  "Robert A. Heinlein's The Puppet Masters (1994)"
]

### 推論フィルターの利用
#### 推論フィルターの作成
ここではActionジャンルのみを出力する推論フィルターを作成

In [ ]:
filter_expression = 'INCLUDE ItemID WHERE Items.GENRE IN ("Action")'

create_filter_response = personalize.create_filter(
    datasetGroupArn = dataset_group_arn,
    filterExpression = filter_expression,
    name = 'genre_filter_action'
)
filter_arn = create_filter_response['filterArn']
print(json.dumps(create_filter_response, indent=2))

{
  "filterArn": "arn:aws:personalize:ap-northeast-1:155580384669:filter/genre_filter_action",
  "ResponseMetadata": {
    "RequestId": "d9435180-fab1-4efa-8f6f-e84480a20b4e",
    "HTTPStatusCode": 200,
    "HTTPHeaders": {
      "content-type": "application/x-amz-json-1.1",
      "date": "Thu, 12 Nov 2020 12:55:39 GMT",
      "x-amzn-requestid": "d9435180-fab1-4efa-8f6f-e84480a20b4e",
      "content-length": "90",
      "connection": "keep-alive"
    },
    "RetryAttempts": 0
  }
}

In [ ]:
status = None
max_time = time.time() + 3*60*60 # 3 hours
while time.time() < max_time:
    describe_filter_response = personalize.describe_filter(
        filterArn = filter_arn
    )
    status = describe_filter_response["filter"]["status"]
    print('.',end='')
    
    if status == "ACTIVE" or status == "CREATE FAILED":
        print('!')
        print(f"Filter: {status}")
        break
        
    time.sleep(20)

..

#### 推論フィルターを指定せずにレコメンデーションのリストを取得

In [66]:
get_recommendations_response = personalize_runtime.get_recommendations(
    campaignArn = user_personalization_campaign_arn,
    userId = '10'
)

item_list = get_recommendations_response['itemList']
title_list = [item_data.loc[item_data['ITEM_ID'] == np.int(item['itemId'])].values[0][1] for item in item_list]

print("Recommendations: {}".format(json.dumps(title_list, indent=2)))

Recommendations: [
  "Congo (1995)",
  "Time Tracers (1995)",
  "Angel on My Shoulder (1946)",
  "Bent (1997)",
  "Outlaw, The (1943)",
  "Free Willy (1993)",
  "Heaven & Earth (1993)",
  "Jason's Lyric (1994)",
  "Johnny 100 Pesos (1993)",
  "Beyond Bedlam (1993)",
  "Lashou shentan (1992)",
  "Newton Boys, The (1998)",
  "Farinelli: il castrato (1994)",
  "Normal Life (1996)",
  "MURDER and murder (1996)",
  "Big Bang Theory, The (1994)",
  "Clean Slate (Coup de Torchon) (1981)",
  "Simple Twist of Fate, A (1994)",
  "Somebody to Love (1994)",
  "Gang Related (1997)",
  "Entertaining Angels: The Dorothy Day Story (1996)",
  "Dingo (1992)",
  "Two or Three Things I Know About Her (1966)",
  "Guilty as Sin (1993)",
  "Men of Means (1998)"
]